### ISSUE TITLE
Waypoints redundant?

### ISSUE THREAD

**Issue by dodexahedron** [Tyrsis/SE-Community-Mod-API#36]
Now that the GPS feature is in the game, should waypoints be removed all together?
I've got a code commit ready that removes the feature.

**Comment by dodexahedron** [comment]
I suppose I should have left this comment on the essentials plugin...  Re-posting over there for organization's sake.

**Comment by rogeriocamorim** [comment]
No becouse you can add Waypoint to every one via server.

Abraços Rogerio Camorin
Em 23/01/2015 17:39, "dodexahedron" <notifications@github.com> escreveu:

**Comment by McyD** [comment]
not to mention that keens poor clone of this does not let it be set to faction/hostile/neutral, and as far as I know is not toggle-able.  Though I could be wrong on that part, as since the way-points works so well I have not even looked at keens version.
