### ISSUE TITLE
Entities Tab - Is there a way to sort by Distance or Alpabetical

### ISSUE THREAD

**Issue by furtivesage** [Tyrsis/SE-Community-Mod-API#59]
Great program and this is not really an issue but more of a convenience - when I am looking to scrub pesky npc ships or clutter it is much easier to do it by looking at objects clustered in similar distances.  Also, alphabetical sorting has its obvious advantages.

**Comment by furtivesage** [comment]
Nevermind, out of all this time I never realized the tab at the bottom of the screen is changeable.. Closing the comment.  Sorry about that.

**Comment by dodexahedron** [comment]
Glad you found what you needed. :)
