### ISSUE TITLE
Failed to find Methods

### ISSUE THREAD

**Issue by fo0** [Tyrsis/SE-Community-Mod-API#60]
When i start Essentials, i get this Message, but the "mod" still works, only just an information.

Finished loading LogManager
Finished loading SandboxGameAssemblyWrapper
2015-03-11 01:04:44.653 - Failed to find method '8E7BC1DD3210BE59E40E80F593E597D
D' in type 'C42525D7DE28CE4CFB44651F3D03A50D.3B0B7A338600A7B9313DE1C3723DAD14'
2015-03-11 01:04:44.653 - Failed to find method 'F924262370F6E7B576D4317EE65B49A
3' in type 'C42525D7DE28CE4CFB44651F3D03A50D.3B0B7A338600A7B9313DE1C3723DAD14'
ServerNetworkManager reflection validation failed!
All entity types passed reflection unit tests!
All block types passed reflection unit tests!

**Comment by dodexahedron** [comment]
You're using version 1.72.06 on a version of SE that is not version 1.72.06.
That method is the old method for banning users.
Please be sure to always update SESE when you update SE, and only run the version of SESE that matches the version of SE you are using.  The version can be seen in the properties of SEServerExtender.exe, and the first three numbers will always match the version of Space Engineers that that release of SESE works with.

**Comment by fo0** [comment]
Im "pretty sure", that im using on both sides the latest version.
In addition, i tried to reinstall the "mods" again. Still got the same problems ... :-S, maybe it has something to do with the "old" map ?

**Comment by fo0** [comment]
Problems fixed after the latest update - mins ago. Thanks a lot. Great Job.
closed.
